[workspace]
members = [
    "tasks/e_resourceful_caterpillar_sequence",
    "tasks/d_refined_product_optimality",
    "tasks/c_bewitching_stargazer",
    "tasks/b_outstanding_impressionist",
    "tasks/a_tender_carpenter",
    "main",
    "algo_lib",
]
resolver = "2"
