[package]
name = "d_move_back_at_acost"
version = "0.1.0"
edition = "2021"

[dependencies]
algo_lib = { path = "../../algo_lib" }

[build-dependencies]
rust_competitive_helper_util = {git = "https://github.com/rust-competitive-helper/rust-competitive-helper"}
